### ISSUE TITLE
Make CLI build

### ISSUE THREAD

**Issue by sofusalbertsen** [praqma-training/artifactory-katas#34]
Make a build call that uses bash instead.

**Comment by sofusalbertsen** [comment]
@bicschneider or @MichaelMadsen can you help me sanity check this exercise?
https://github.com/praqma-training/artifactory-kata/tree/master/cli_build

**Comment by figaw** [comment]
Went through the entire exercise. Everything makes sense.

I did experience something funny tho.
- I first published an artifact without buildname/number
- I then published my `env` with `bce` and a build with `bp`
- I then tried to republish the artifact with the buildname/number used above, but it didn't show up as an artifact under the build
- I then republished my build with `bp` and another build appeared, with same name and id, and the artifact was connected to it
- I could promote it afterwards.

I think it makes sense because, a build should be immutable, so after publishing it you're not allowed to make changes, and publishing the build is the last thing you do.

@sofusalbertsen you can close this if you're happy.

**Comment by figaw** [comment]
I published the same artifact under a different build, and now it shows up under both builds because of the deduplication / reference to the actual file. I'm pretty sure I'm sort of abusing artifactory right now, so it's doing funny stuff.

I was competely able to 1: upload a new artifact with build name/number, 2: publish a build registering the module.

**Comment by sofusalbertsen** [comment]
Sweet @figaw  and thanks a bunch for all your work on these!
